#! /bin/sh
# /etc/init.d/swift-ring-master

### BEGIN INIT INFO
# Provides:          swift-ring-master
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the swift-ring-master server
# Description:       starts the swift-ring-master server using start-stop-daemon
### END INIT INFO

SWIFT_USER=swift

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting swift-ring-master"
        su $SWIFT_USER -s /bin/bash -c "/usr/bin/swift-ring-master-server start --conf=/etc/swift/ring-master.conf"
        ;;
    stop)
        echo "Stopping swift-ring-master"
        su $SWIFT_USER -s /bin/bash -c "/usr/bin/swift-ring-master-server stop --conf=/etc/swift/ring-master.conf"
        ;;
    *)
        echo "Usage: /etc/init.d/swift-ring-master {start|stop}"
        exit 1
        ;;
esac

exit 0
