#! /bin/sh
# /etc/init.d/swift-ring-minion

### BEGIN INIT INFO
# Provides:          swift-ring-minion
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the swift-ring-minion server
# Description:       starts the swift-ring-minion server using start-stop-daemon
### END INIT INFO

CONF="/etc/swift/ring-minion.conf"
DIRNAME=$(dirname `which swift-ring-minion-server`)

if [ ! -e /var/run/swift ]; then
  mkdir /var/run/swift
fi

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting swift-ring-minion"
        $DIRNAME/swift-ring-minion-server start --conf=$CONF
        ;;
    stop)
        echo "Stopping swift-ring-minion"
        $DIRNAME/swift-ring-minion-server stop --conf=$CONF
        ;;
    restart)
        echo "Restarting swift-ring-minion"
        $DIRNAME/swift-ring-minion-server stop --conf=$CONF
        $DIRNAME/swift-ring-minion-server start --conf=$CONF
        ;;
    *)
        echo "Usage: /etc/init.d/swift-ring-minion {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
